-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7JXVJtuoSIz57yZP
cgdJUoPGctN3RElx+/gj8wibqKygCgYIKoZIzj0DAQehRANCAAQSjGhVBubimlFA
Rfe8j4E9CgVV3IseAnleyT4uU98usyqdGtJA01UONr9khgfvhyADTGnW0GeyN7I1
roJycgQJ
-----END PRIVATE KEY-----